config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'index', to: 'recipes#index'
  root 'recipes#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    resources :recipes,except: :index  do
      get :view, on: :member
      get :dislike, on: :member
      get :favorite, on: :member
      resources :ingredients
      resources :steps
      resources :comments
      resources :dislikes
      resources :favorites
    end
  end


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many  :ingredient, :dependent => :destroy
  has_many  :steps, :dependent => :destroy
  has_many  :comment, :dependent => :destroy
  has_many  :dislike, :dependent => :destroy
  has_many  :favorite, :dependent => :destroy
  before_save { self.name = name.downcase}
  before_save { self.origin = origin.downcase}
  has_attached_file :image, style: { medium: "300x300>", thumb: "150x150#"}, :dependent => :destroy
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_attached_file :video, :styles => {:medium => { :geometry => "300x300", :format => 'flv'},:thumb => {:geometry => "100x100#", :format => 'jpg', :time => 15}
    }, :processors => [:ffmpeg], :dependent => :destroy
  validates_attachment_content_type :video, content_type: %w(video/mp4 video/3gp video/webm image/jpeg image/jpg image/png)
  validates :name, presence:true
  validates :origin, presence:true

  def self.check_dislike recipe, user
    @recipe = Recipe.find(recipe.id)
    @recipe.favorite.each {|f| return true if f.user_id == user.id}
    @recipe.dislike.each {|d| return true if d.user_id == user.id}
    false
  end

  def self.check_favorite recipe, user
    @recipe = Recipe.find(recipe.id)
    @recipe.dislike.each {|d| return true if d.user_id == user.id}
    @recipe.favorite.each {|f| return true if f.user_id == user.id}
    false
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_user,only: [:new,:edit,:update,:show,:destroy,:create]
  before_action :require_user, except: [:index,:view]
  before_action :require_same_user, only: [:edit,:update,:show,:destroy]

  def index
    @recipe = Recipe.all.order(created_at: :desc)
    return @recipe = Recipe.where("name LIKE ? ", "%#{params[:search_field].downcase}%").all if params[:search] == 'name'
    return @recipe = Recipe.where("origin LIKE ? ", "%#{params[:search_field].downcase}%").all if params[:search] == 'origin'
    return @recipe = Recipe.joins(:user).where(:users => {:name => "#{params[:search_field].downcase}"})  if params[:search] =='create_by'

  end


  def new
    @recipe = @user.recipes.build
  end

  def create
    @recipe = @user.recipes.create(recip_params)
    if @recipe.save
      flash[:success] = 'Recipe was successfully created'
      redirect_to user_recipe_path(@user.id, @recipe)
    else
      render 'new'
    end
  end

  def edit
    @recipe = @user.recipes.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @recipe = @user.recipes.find(params[:id])
    if params[:format]
      @recipe.update_attribute(:dislike,"#{params[:format].to_i}")
    end
    redirect_to user_path(@user.id) if @recipe.update(recip_params)
  end


  def show
    @recipe = @user.recipes.find(params[:id])
  end

  def destroy
    @recipe =  @user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to user_path(@user.id)
  end

  def view
    @recipe = Recipe.find(params[:id])
    @recipe_all =Recipe.all;
  end

  def dislike
     @user = User.find(params[:user_id])
     @recipe = Recipe.find(params[:id])
     @check = Recipe.check_dislike(@recipe,@user)
     if @check
      flash[:danger] = "u can only dislike or love it once"
      redirect_to root_path
     else
      redirect_to user_recipe_dislikes_path(@user,@recipe)
     end
  end

   def favorite
     @user = User.find(params[:user_id])
     @recipe = Recipe.find(params[:id])
     @check = Recipe.check_favorite(@recipe,@user)
     if @check
      flash[:danger] = "u can only dislike or love it once"
      redirect_to root_path
     else
     redirect_to user_recipe_favorites_path(@user,@recipe)
     end
  end


   private
  def recip_params
    params.require(:recipe).permit(:name, :origin, :description, :image, :video)
  end

  def require_same_user
    @recipe = @user.recipes.find(params[:id])
    if current_user != @recipe.user
      flash[:denger] = 'you can only edit or delete your recipe'
      redirect_to root_path
    end
  end

   def set_user
    @user = User.find(params[:user_id])
  end

end

app/views/recipes/edit.html.erb
<h1 class = 'center'> edit Recip </h1>

<% if @recipe.errors.any?%>
  <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg%></li>
    <%end%>
  </ul>
<%end%>
<div class="container">


<%= form_for @recipe, url: user_recipe_path(@user.id,@recipe.id), html: {method: "put"}, html: { multipart: true } do |f|%>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter name"%>
  </div>
   <div class="form-group">
    <%= f.label :origin%>
   <%= f.text_field :origin, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter Coutry of Origin"%>
  </div>
   <div class="form-group">
   <%= f.label :description%>
  <%= f.text_area :description, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1"%>
  </div>

   <div class="form-group">
   <%= f.label :image%>
  <%= f.file_field :image, :class=>"form-control-file ", :id=>"exampleInputEmail1"%>
  </div>
  <div class="form-group">
   <%= f.label :video%>
  <%= f.file_field :video, :class=>"form-control-file ", :id=>"exampleInputEmail1"%>
  </div>
    <%= f.submit  :class=>'btn btn-success btn-lg' %>
<%end%>
</div>

app/views/recipes/index.html.erb
<div class = 'container '>
  <% @recipe.each do |recipe | -%>
    <div class="card mb-3 ">
       <%= link_to  view_user_recipe_path(recipe.user.id, recipe.id), method: :get, :class=>'nopadding' do %>
        <div class="card-header bckg" style="background-image: url(<%= recipe.image.url %>)">
       </div>
       <%end%>
      <div class="card-body">
        <div class="card-header bg-info">
        <small class=" text-light">Name: <%=recipe.name%></small><br/>
         <small class=" text-light">Origin: <%=recipe.origin%></small><br/>
         <small class=" text-light">Created_by: <%=recipe.user.name%></small>
         </div>
          <blockquote class="blockquote">
            <small class="text-muted"><p class="lead text-size" ><%= recipe.description%></p></small>
            <footer class="blockquote-footer">description</footer>
          </blockquote>

       </div>
       <div class="card-footer">
          <div class="row">
            <div class="col-sm">
              <span class="comment-view">
                <%= link_to 'view', view_user_recipe_path(recipe.user.id, recipe.id), method: :get, :class=>'card-view-comment text-warning'%>
                <a href='#' class="card-view-comment text-warning" data-toggle="modal" data-target="#Modal<%=recipe.id%>">comment</a>
                <span class="dot"><%=recipe.comment.count%></span>
              </span>
            </div>

            <div class="col-sm">
              <span class='love-dislike'>
                <span class="dot"><%=recipe.dislike.count%></span>
                <%if current_user%>
                <%= link_to '<i class="material-icons text-warning">thumb_down</i>'.html_safe, dislike_user_recipe_path(current_user, recipe.id),:class=> "dislike"%>
                <%else%>
                  <%= link_to '<i class="material-icons text-warning">thumb_down</i>'.html_safe, dislike_user_recipe_path( recipe.user.id, recipe.id),:class=> "dislike"%>
                <%end%>
                <span class="dot"><%=recipe.favorite.count%></span>
                <%if current_user%>
                <%= link_to '<i class="material-icons text-danger">favorite</i>'.html_safe,favorite_user_recipe_path(current_user, recipe.id) %>
                <%else%>
                  <%= link_to '<i class="material-icons text-danger">favorite</i>'.html_safe,favorite_user_recipe_path(recipe.user.id, recipe.id) %>
                <%end%>

              </span>
            </div>

            <div class="col-sm">
              <span class= "time-card">
                <small class="text-muted"> Created <%= time_ago_in_words(recipe.created_at)%> ago</small>
                <small class="text-muted"> | Last Update <%= time_ago_in_words(recipe.updated_at)%> ago</small>
              </span>
            </div>

          </div>
       </div>
    </div>


  <%end%>
</div>
  <%= render 'layouts/footer' %>
<%= render 'layouts/comment_model' %>











<!-- model trigger-->

app/views/recipes/new.html.erb
<% if @recipe.errors.any?%>
  <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg%></li>
    <%end%>
  </ul>
<%end%>

<div class= 'container'>
<h1 class = 'text-center'> Create new Recipe </h1>
<%= form_for @recipe, url: user_recipes_path(@user.id),html: { multipart: true } do |f|%>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter name"%>
  </div>
   <div class="form-group">
    <%= f.label :origin%>
   <%= f.text_field :origin, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter Coutry of Origin"%>
  </div>
   <div class="form-group">
   <%= f.label :description%>
  <%= f.text_area :description, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1"%>
  </div>

   <div class="form-group">
   <%= f.label :image%>
  <%= f.file_field :image, :class=>"form-control-file ", :id=>"exampleInputEmail1"%>
  </div>

  <div class="form-group">
   <%= f.label :video%>
  <%= f.file_field :video, :class=>"form-control-file ", :id=>"exampleInputEmail1"%>
  </div>
    <%= f.submit  :class=>'btn btn-success btn-lg' %>
<%end%>
</div>

app/views/recipes/show.html.erb
<header class="foobar" style="background-image: url(<%= @recipe.image.url %>)"></header>
<div class="card-body">
    <div class="card-header bg-info">
    <small class="text-light">Name: <%=@recipe.name%></small><br/>
    <small class="text-light">Origin: <%=@recipe.origin%></small><br/>
    <small class="text-light">Created_by: <%=@recipe.user.name%></small>
    </div>
</div>
  <div class="card-body">
    <blockquote class="blockquote">
    <small class="text-muted"><p class="lead text-size" ><%= @recipe.description%></p></small>
     <footer class="blockquote-footer">description</footer>
    </blockquote>
  </div>
  <div class="card-footer text-muted shadow-lg p-3 mb-5 footer-view_color rounded">
      <div class="row">
         <div class="col-sm ">
            <div class="row">
                <div class="col-sm">
                  <span class="dot"><%=@recipe.dislike.count%></span>
                  <i class="material-icons text-info">thumb_down</i>
                </div>
            <div class="col-sm">
                <span class="dot"><%=@recipe.favorite.count%></span>
                <i class="material-icons text-danger">favorite</i>
            </div>
          </div>

         </div>


          <div class="col-sm display">
            <%= link_to '<i class="material-icons text-danger">delete recipe</i>'.html_safe ,user_recipe_path(@user.id,@recipe.id),method: :delete, data: {confirm: "are you sure want to delete this recipe?"},:class=>"no-padding"%>
  <%= link_to '<i class="material-icons ">edit recipe</i>'.html_safe ,edit_user_recipe_path(@user.id,@recipe.id), :class=>"no-padding"%>
         </div>
          <div class="col-sm">
              <span class= "time-card">
                <small class="text-muted"> Created <%= time_ago_in_words(@recipe.created_at)%> ago</small>
                <small class="text-muted"> | Last Update <%= time_ago_in_words(@recipe.updated_at)%> ago</small>
              </span>
            </div>
      </div>


  </div>

<div class='container'>
<%= form_tag(user_recipe_ingredients_path(@user.id, @recipe.id),method: :post) do |f|%>
 <div class="row">
    <div class="col">
      <%= label_tag :ingredient, "Ingredient" %>
      <%= text_field_tag :ingredient, "", class: 'form-control' %>
     </div>
     <div class="col">
      <%= label_tag :qty, "Qty" %>
      <%= text_field_tag :qty, "", class: 'form-control' %>
     </div>

  </div>
  <%= submit_tag "Add Ingredient",class:'btn btn-success btn-add_ing' %>
<%end%>




<h5 class ='text-center text-uppercase font-weight-light '> list of ingredient</h5>

  <table class="table">
    <tr>
      <th>Ingredient</th>
      <th>Qty</th>
      <th>create at</th>
      <th></th>
      <th></th>
    </tr>
    <% @recipe.ingredient.each do |ingredients| -%>
      <tr>
        <td><%= ingredients.ingredient%></td>
        <td><%= ingredients.qty%></td>
        <td><%= ingredients.created_at%></td>
        <td><%= link_to '<i class="material-icons text-danger">delete</i>'.html_safe, user_recipe_ingredient_path(@user.id ,@recipe.id,ingredients.id),method: :delete, data: {confirm: "are you sure?"} %></td>
        <td><%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_user_recipe_ingredient_path(@user.id,@recipe.id,ingredients.id) %></td>

      </tr>
    <% end -%>

  </table>


<%= form_tag(user_recipe_steps_path(@user.id, @recipe.id),method: :post) do |f|%>
 <div class="form-group ">
  <%= text_field_tag :step, "", class: 'form-control input-margin-top',placeholder:"enter the steps here" %>
  </div>
  <%= submit_tag "Add step",class:'btn btn-success' %>
<%end%>

<h5 class = 'text-center text-uppercase font-weight-light'> list of Steps</h4>

  <table class="table">
    <%@recipe.steps.each do |step| -%>
     <tr>
        <td><%= step.step%></td>
        <td><%= link_to '<i class="material-icons text-danger">delete</i>'.html_safe, user_recipe_step_path(@user.id,@recipe.id,step.id),method: :delete, data: {confirm: "are you sure?"} %></td>
        <td><%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_user_recipe_step_path(@user.id,@recipe.id,step.id) %></td>
      </tr>
    <%end-%>
  </table>

  </div>

app/views/recipes/view.html.erb
<header class="foobar" style="background-image: url(<%= @recipe.image.url %>)"></header>
 <div class="card-body">
 <div class="card-header  bg-info ">
    <small class="text-light">Name: <%=@recipe.name%></small><br/>
    <small class="text-light">Origin: <%=@recipe.origin%></small><br/>
    <small class="text-light">Created_by: <%=@recipe.user.name%></small>
  </div>
  </div>
  <div class="card-body">
    <blockquote class="blockquote">
    <small class="text-muted"><p class="lead text-size" ><%= @recipe.description%></p></small>
     <footer class="blockquote-footer">description</footer>
    </blockquote>
  </div>
  <div class="card-footer text-muted shadow-lg p-3 mb-5 footer-view_color rounded">
  <div class="row">
            <div class="col-sm">
              <span class="comment-view">
                <a href='#' class="card-view-comment text-warning" data-toggle="modal" data-target="#Modal<%=@recipe.id%>">comment</a>
                <span class="dot"><%=@recipe.comment.count%></span>
              </span>
            </div>

            <div class="col-sm">
              <span class='love-dislike'>
                <span class="dot"><%=@recipe.dislike.count%></span>
                <%= link_to '<i class="material-icons text-warning">thumb_down</i>'.html_safe, user_recipe_dislikes_path(@recipe.user.id, @recipe.id,1),:class=> "dislike"%>
                <span class="dot"><%=@recipe.favorite.count%></span>
                <%= link_to '<i class="material-icons text-danger">favorite</i>'.html_safe,user_recipe_favorites_path(@recipe.user.id, @recipe.id,1)%>

              </span>
            </div>

            <div class="col-sm">
              <span class= "time-card">
                <small class="text-muted"> Created <%= time_ago_in_words(@recipe.created_at)%> ago</small>
                <small class="text-muted"> | Last Update <%= time_ago_in_words(@recipe.updated_at)%> ago</small>
              </span>
            </div>

          </div>
  </div>

  <div class="container-view">
  <div class="row">
  <div class="col-6">
<h5 class ='text-center'> list of ingredient</h5>
  <table class="table">
    <tr>
      <th></th>
      <th>Ingredient</th>
      <th>Qty</th>
      <th>create at</th>
    </tr>
    <% @recipe.ingredient.each do |ingredients| -%>
      <tr>
        <th id="counter" class="dot-big">1</th>
        <td><%= ingredients.ingredient%></td>
        <td><%= ingredients.qty%></td>
        <td><%= ingredients.created_at%></td>
      </tr>
    <% end -%>

  </table>

  </div>
    <div class="col-6">
<h5 class = 'text-center'> list of Steps</h4>

  <table class="table">
    <%@recipe.steps.each do |step| -%>
     <tr>
        <th id="counter" class="dot-big">1</th>
        <td><%= step.step%></td>
      </tr>
    <%end-%>
  </table>

  </div>
</div>
<hr>
 <div class="col-6">
      <% if @recipe.video%>
      <%=video_tag(@recipe.video.url, controls: true, autobuffer: true,class:'video_mobile')%>
      <%end%>
  </div>
</div>


<%@recipe_all.each do |recipe | -%>
<div class="modal fade" id="Modal<%=recipe.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel">Comments</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <ul class="list-group list-group-flush">
        <%recipe.comment.each do |c|%>
            <li class="list-group-item"><%= image_tag 'avatar.png', class:"avatar", alt:"Avatar"%><span class="badge badge-pill badge-primary"><%=Comment.find(c.id).user.name%></span>:  <%=c.comment%></li>
        <%end%>
         </ul>
      </div>
      <div class="modal-footer">
       <%if current_user%>
        <%= form_tag(user_recipe_comments_path(recipe.user.id, recipe.id, current_user),method: :post) do |f|%>
              <div class="row">
                <div class="col">
                  <%= text_field_tag :comment,"" ,class:'form-control',placeholder:"Enter comment" %>
                </div>
                <div class="col">
                  <%= submit_tag "add comment",class:'btn btn-success'%>
                </div>
             </div>
          <%end%>
          <%else%>
           <%= form_tag(user_recipe_comments_path(recipe.user.id, recipe.id),method: :post) do |f|%>
              <div class="row">
                <div class="col">
                  <%= text_field_tag :comment,"" ,class:'form-control',placeholder:"Enter comment" %>
                </div>
                <div class="col">
                  <%= submit_tag "add comment",class:'btn btn-success'%>
                </div>
             </div>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>
<%end%>