config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'index', to: 'recipes#index'
  root 'recipes#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    resources :recipes,except: :index  do
      get :view, on: :member
      get :dislike, on: :member
      get :favorite, on: :member
      resources :ingredients
      resources :steps
      resources :comments
      resources :dislikes
      resources :favorites
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, :dependent => :destroy
  has_many :comment, :dependent => :destroy
  has_one :dislike,:dependent => :destroy
  has_one :favorite,:dependent => :destroy
  before_save { self.email = email.downcase}
  before_save { self.name = name.downcase}
  validates :name, presence:true, length: {minimum:3, maximum:50}
  VALID_EMAIL_REGX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, uniqueness: {case_sensitive: false},format: {with:VALID_EMAIL_REGX}

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_user, except: [:new,:create]
    before_action :require_same_user, only: [:edit,:update,:show,:destroy]

  def new
    @user = User.new
  end

  def index
    @user = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id #allow to login when registered
      flash[:success] = 'Profile was successfully created'
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully'
      redirect_to users_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :phone)
  end

   def require_same_user
    if current_user != @user
      flash[:denger] = 'you can only acess your account'
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end




end

app/views/users/edit.html.erb
<%= render 'layouts/messages' %>
<div class= 'container'>

<%= form_for @user do |f|%>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter name"%>
  </div>
   <div class="form-group">
    <%= f.label :phone%>
   <%= f.phone_field :phone, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter Phonr number"%>
  </div>
   <div class="form-group">
    <%= f.label :email%>
   <%= f.email_field :email, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter email"%>
  </div>
  <div class="form-group">
   <%= f.label :password%>
   <%= f.password_field :password, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Password"%>
  </div>
    <%= f.submit 'Sign Up', :class => 'btn btn-success' %>
<%end%>




</div>

app/views/users/new.html.erb
<%= render 'layouts/messages' %>
<div class= 'container'>
<h1 class = 'text-center'> Sign Up</h1>
<hr/>
<%= form_for @user do |f|%>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter name"%>
  </div>
   <div class="form-group">
    <%= f.label :phone%>
   <%= f.phone_field :phone, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter Phonr number"%>
  </div>
   <div class="form-group">
    <%= f.label :email%>
   <%= f.email_field :email, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Enter email"%>
  </div>
  <div class="form-group">
   <%= f.label :password%>
   <%= f.password_field :password, autofocus: true, :class=>"form-control", :id=>"exampleInputEmail1", :placeholder=>"Password"%>
  </div>
    <%= f.submit 'Sign Up', :class => 'btn btn-success' %>
<%end%>




</div>

app/views/users/show.html.erb
<div class="container">
<h1 class="text-center">Your recipes</h1>

 <table class="table">
    <tr>
      <th>Name</th>
      <th>Origin</th>
      <th>create at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <%@user.recipes.each do |recipe| -%>
     <tr>
        <td><%= recipe.name%></td>
        <td><%= recipe.origin%></td>
        <td><%= recipe.created_at%></td>
        <td><%= link_to 'view' ,user_recipe_path(@user.id,recipe.id)%></td>
        <td> <%= link_to '<i class="material-icons text-danger">delete</i>'.html_safe,user_recipe_path(@user.id,recipe.id),method: :delete, data: {confirm: "are you sure?"}  %></td>
        <td><%= link_to '<i class="material-icons">edit</i>'.html_safe ,edit_user_recipe_path(@user.id,recipe.id)%></td>
      </tr>
    <%end-%>
  </table>
<%= link_to 'create a recipe', new_user_recipe_path(@user.id) , :class=>'btn btn-success btn-lg'%>

</div>