config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'index', to: 'recipes#index'
  root 'recipes#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    resources :recipes,except: :index  do
      get :view, on: :member
      get :dislike, on: :member
      get :favorite, on: :member
      resources :ingredients
      resources :steps
      resources :comments
      resources :dislikes
      resources :favorites
    end
  end


end

app/views/layouts/_comment_model.html.erb
 <% @recipe.each do |recipe | -%>
<div class="modal fade" id="Modal<%=recipe.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel">Comments</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <ul class="list-group list-group-flush">
        <%recipe.comment.each do |c|%>
            <li class="list-group-item"><%= image_tag 'avatar.png', class:"avatar", alt:"Avatar"%><span class="badge badge-pill badge-primary"><%=Comment.find(c.id).user.name%></span>:  <%=c.comment%></li>
        <%end%>
         </ul>
      </div>
      <div class="modal-footer">
       <%if current_user%>
        <%= form_tag(user_recipe_comments_path(recipe.user.id, recipe.id, current_user),method: :post) do |f|%>
              <div class="row">
                <div class="col">
                  <%= text_field_tag :comment,"" ,class:'form-control',placeholder:"Enter comment" %>
                </div>
                <div class="col">
                  <%= submit_tag "add comment",class:'btn btn-success'%>
                </div>
             </div>
          <%end%>
          <%else%>
           <%= form_tag(user_recipe_comments_path(recipe.user.id, recipe.id),method: :post) do |f|%>
              <div class="row">
                <div class="col">
                  <%= text_field_tag :comment,"" ,class:'form-control',placeholder:"Enter comment" %>
                </div>
                <div class="col">
                  <%= submit_tag "add comment",class:'btn btn-success'%>
                </div>
             </div>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>
<%end%>

app/views/layouts/_flash_message.html.erb
<div class ="container-flash">
<div class="row row-padding">
    <div class="col-xs-10 col-xs-offset-1 full-width">
    <% flash.each do |key, value| %>
      <div role="alert" class=" alert-dismissible fade show alert alert-<%= key %>"><%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>

      </div>
      <% end %>
    </div>
</div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small  pt-4 bg-dark">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-center">

      <!-- Grid row -->


          <!-- Content -->
          <h5 class="text-light h4">Food-up</h5>
          <small class='text-size'>FoodUp is an application that allow you to share your culcute through gastronomy
          share your Recipe Food or Drink, let other know :)
          </small>


        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">
          </div>
          <!-- Grid column -->


    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3   bg-copyright">© 2018 Copyright:
      CraftByts
    </div>
    <!-- Copyright -->

  </footer>

app/views/layouts/_messages.html.erb
<div class="container errors">
<% if @user.errors.any?%>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="alert alert-danger alert-dismissible fade show"" role="alert">
        <h4 class="alert-heading">Erros fix in order to sign up...</h4>
        <ul>
          <% @user.errors.full_messages.each do |msg|%>
          <li><%= msg%></li>
          <%end%>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<%end%>
</div>

app/views/layouts/_navBar.html.erb
<nav class="navbar navbar-expand-lg  fixed-top navbar-dark bg-dark">
  <a class="navbar-brand text-light" href="/">FoodUp <small class= 'text-muted text-logo'>share your culture</small></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto float-right">
      <li class="nav-item active ">
        <%= link_to 'Home',root_path, :class=>"nav-link"%>
      </li>
       <%if logged_in?%>
       <li class="nav-item">
        <i class='material-icons text-white'>person_pin</i>
      </li>
      <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <%= user_name%>
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <%= link_to 'View Profile', user_path(current_user),:class=>"dropdown-item"  %>
         <%= link_to 'Edit Profile', edit_user_path(current_user),:class=>"dropdown-item"  %>
          <div class="dropdown-divider"></div>
           <%= link_to 'Log Out', logout_path,method: :delete,:class=>"dropdown-item"  %>
        </div>
      </li>
      <%else%>
          <li class="nav-item">
              <%= link_to 'Log In', login_path ,:class=>"nav-link "%>
          </li>
           <li class="nav-item">
              <%= link_to 'Sign Up', new_user_path ,:class=>"nav-link" %>
          </li>
      <%end%>
    </ul>
    <%= form_tag(index_path, method: "get", class: 'form-inline my-2 my-lg-0 mx-auto') do %>
      <%= text_field_tag :search_field,"", class: 'form-control mr-sm-2', placeholder: 'search recipes' %>
      <%= submit_tag "Search",class:"btn btn-success btn-search" %>
      <%= radio_button_tag :search, "name",class:'form-control search_name' %>
      <%= label_tag :reccipe_name, "name", class: 'text-white ' %>
      <%= radio_button_tag(:search, "origin") %>
      <%= label_tag :recipe_origin, "origin", class: 'text-white'%>
      <%= radio_button_tag(:search, "create_by") %>
      <%= label_tag :recipe_creater, "creater",class: 'text-white' %>
    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navBar' %>
  <%= render 'layouts/flash_message' %>
  </div>
    <%= yield %>


  </body>
</html>